### ISSUE TITLE
Unify functionality for history search

### ISSUE THREAD

**Issue by sholderbach** [jntrnr/reedline#55]
Currently there are two ways to search the `History`. 

1. There is the `history_search::BasicSearch` implementation used to provide the `Ctrl+R` backwards search. 
  - It is integrated with a modal search prompt but lacks functionality to walk the search back and forward
  - seems to have accumulated some issues due to unrelated development (Using the arrow keys breaks the prompt)
  - Independent struct more amenable in an API to use more advanced search providers (e.g. fuzzy matching)

2. `History` itself now provides a simple stateful prefix search.
  - Keeps track of cursor and searches based on that -> up and down very easy. 
  - More readable and self contained search logic
  - Managing the search prefix is up to the user.

**Comment by sherubthakur** [comment]
@sholderbach I think we can close this. Right?

**Comment by sholderbach** [comment]
Yes!
