### ISSUE TITLE
[Bug] History command disappear after few seconds + cursor position not updated with history command len

### ISSUE THREAD

**Issue by mzanrosso** [jntrnr/reedline#94]
Step to reproduce:
- Checkout main
- Cargo run 
- Type a command
- Use low arrow to navigate the history
- Wait few seconds

![Registrazione schermo 2021-07-09 alle 22 04 12](https://user-images.githubusercontent.com/51322105/125130811-efd71800-e101-11eb-9d99-5e18e8661859.gif)

**Comment by sholderbach** [comment]
When reproducing I also noticed that the move up displayed the second last entry from the history

**Comment by sherubthakur** [comment]
These are most likely introduced by https://github.com/jntrnr/reedline/pull/92, which I worked on earlier. 

### Problem
Cursor position update

### Potential Culprit
https://github.com/jntrnr/reedline/pull/92/files#diff-ff278ec599adfd033d35a083ebe8948db8bf177c9817dee8ddc4f3a9e3f5728eR694.

### Potential Fix
- Probably this function should handle the update to the cursor. 
- Afterwards, if there is a char insert we copy over the history result to line_buffer.

### Problem
Last entry is not shown

### Potential Cluprit
hitting back calls the previous history, which increments the cursor position.

### Potential Fix
display first then perform move. Thoughts?

### Problem
History command disappear after few seconds

I am not sure why this could be happening. 

_I really should have added more tests to engine as well_

**Comment by mzanrosso** [comment]
@sherubthakur Yes, these problems have been introduced with the last commit; in fact if you run:
```
git checkout main
git reset --soft HEAD~1
git stash ; git stash clear
cargo run
```
You will notice that these problems have disappeared

**Comment by sherubthakur** [comment]
> these problems have been introduced with the last commit; in fact if you run:

I believe the disappearing of history commands already existed with `ctrl-R` search, and the unification got this into prefix search as well.
